### ISSUE TITLE
ESP8266 with serial connection

### ISSUE THREAD

**Issue by Binh2542** [MrYsLab/Telemetrix4Esp8266#10]
How can i use ESP8266 with serial connection instead of wifi server?

TelemetrixAIO Version: 1.24
Copyright (c) 2018-2023 Alan Yorinks All rights reserved.

Opening all potential serial ports...

Checking COM9

Waiting 4 seconds(arduino_wait) for Arduino devices to reset...

Searching for an Arduino configured with an arduino_instance =  1
Traceback (most recent call last):
  File "d:\CPRO\AUTO FOCUS\python\Draft2.py", line 127, in <module>
    board = telemetrix_aio.TelemetrixAIO()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\binh2\miniconda3\Lib\site-packages\telemetrix_aio\telemetrix_aio.py", line 270, in __init__
    self.loop.run_until_complete(self.start_aio())
  File "C:\Users\binh2\miniconda3\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\binh2\miniconda3\Lib\site-packages\telemetrix_aio\telemetrix_aio.py", line 308, in start_aio
    raise RuntimeError('No Arduino Found or User Aborted Program')
RuntimeError: No Arduino Found or User Aborted Program

**Comment by Binh2542** [comment]
Thank you, i'll test it soon

**Comment by Binh2542** [comment]
It works perfectly, thanks alot
